//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModels.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewModels.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///   {
        ///      &quot;Rank&quot;: 1,
        ///      &quot;Movie&quot;: &quot;Citizen Kane&quot;,
        ///      &quot;Year&quot;: 1941,
        ///      &quot;Cast&quot;: &quot;Orson Welles, Joseph Cotten, Dorothy Comingore&quot;,
        ///      &quot;Director&quot;: &quot;Orson Welles&quot;
        ///   },
        ///   {
        ///      &quot;Rank&quot;: 2,
        ///      &quot;Movie&quot;: &quot;The Godfather&quot;,
        ///      &quot;Year&quot;: 1972,
        ///      &quot;Cast&quot;: &quot;Marlon Brando, Al Pacino, James Caan&quot;,
        ///      &quot;Director&quot;: &quot;Francis Ford Coppola&quot;
        ///   },
        ///   {
        ///      &quot;Rank&quot;: 3,
        ///      &quot;Movie&quot;: &quot;Casablanca&quot;,
        ///      &quot;Year&quot;: 1942,
        ///      &quot;Cast&quot;: &quot;Humphrey Bogart, Ingrid Bergman, Paul Henreid&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AFITop100_json {
            get {
                return ResourceManager.GetString("AFITop100_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///    {
        ///        &quot;Id&quot;: 1,
        ///        &quot;FirstName&quot;: &quot;Robert&quot;,
        ///        &quot;LastName&quot;: &quot;Kwang&quot;,
        ///        &quot;ReportTo&quot;: 0
        ///    },
        ///    {
        ///        &quot;Id&quot;: 2,
        ///        &quot;FirstName&quot;: &quot;Daniel&quot;,
        ///        &quot;LastName&quot;: &quot;Johnson&quot;,
        ///        &quot;ReportTo&quot;: 1
        ///    },
        ///    {
        ///        &quot;Id&quot;: 3,
        ///        &quot;FirstName&quot;: &quot;Catherine&quot;,
        ///        &quot;LastName&quot;: &quot;Hatwell&quot;,
        ///        &quot;ReportTo&quot;: 1
        ///    },
        ///    {
        ///        &quot;Id&quot;: 4,
        ///        &quot;FirstName&quot;: &quot;David&quot;,
        ///        &quot;LastName&quot;: &quot;Ibrahim&quot;,
        ///        &quot;ReportTo&quot;: 1
        ///    },
        ///    {
        ///        &quot;Id&quot;: 5,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string employees_json {
            get {
                return ResourceManager.GetString("employees_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to First Name.
        /// </summary>
        public static string GridViewVM_FirstName {
            get {
                return ResourceManager.GetString("GridViewVM_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last Name.
        /// </summary>
        public static string GridViewVM_LastName {
            get {
                return ResourceManager.GetString("GridViewVM_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ACME Employees Directory.
        /// </summary>
        public static string GridViewVM_ListTitle {
            get {
                return ResourceManager.GetString("GridViewVM_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type an employee name.
        /// </summary>
        public static string GridViewVM_SearchPlaceHolder {
            get {
                return ResourceManager.GetString("GridViewVM_SearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///   {
        ///      &quot;Id&quot;: 1,
        ///      &quot;Type&quot;:  &quot;Book&quot;,
        ///      &quot;Category&quot;: &quot;Fiction&quot;,
        ///      &quot;Recommended&quot;:  1,
        ///      &quot;Title&quot;: &quot;The Martian&quot;,
        ///      &quot;Author&quot;: &quot;Andy Weir&quot;,
        ///      &quot;Rating&quot;: 4.5,
        ///      &quot;ImageUrl&quot;: &quot;/images/placeholder.png&quot;,
        ///      &quot;ItemUrl&quot;: &quot;&quot;
        ///   },
        ///   {
        ///      &quot;Id&quot;: 2,
        ///      &quot;Type&quot;:  &quot;Book&quot;,
        ///      &quot;Category&quot;: &quot;Fiction&quot;,
        ///      &quot;Title&quot;: &quot;Life Of Pi&quot;,
        ///      &quot;Author&quot;: &quot;Yann Martel&quot;,
        ///      &quot;Rating&quot;: 4.5,
        ///      &quot;ImageUrl&quot;: &quot;/images/placeholder.png&quot;,
        ///      &quot;ItemUrl&quot;: &quot;&quot;
        ///   },
        ///   {
        ///      &quot;Id&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string webstore_json {
            get {
                return ResourceManager.GetString("webstore_json", resourceCulture);
            }
        }
    }
}
